Start testing: Oct 18 14:16 KST
----------------------------------------------------------
1/3 Testing: qa_random_periodic_source
1/3 Test: qa_random_periodic_source
Command: "/bin/sh" "/home/seungmin/git/gr_attack/gr-attack/build/python/qa_random_periodic_source_test.sh"
Directory: /home/seungmin/git/gr_attack/gr-attack/build/python
"qa_random_periodic_source" start time: Oct 18 14:16 KST
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/seungmin/git/gr_attack/gr-attack/build/swig/attack_swig.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/seungmin/git/gr_attack/gr-attack/build/swig/_attack_swig.so: undefined symbol: _ZN2gr6attack13modified_RAPP4makeEv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seungmin/git/gr_attack/gr-attack/python/qa_random_periodic_source.py", line 24, in <module>
    import attack_swig as attack
  File "/home/seungmin/git/gr_attack/gr-attack/build/swig/attack_swig.py", line 17, in <module>
    _attack_swig = swig_import_helper()
  File "/home/seungmin/git/gr_attack/gr-attack/build/swig/attack_swig.py", line 16, in swig_import_helper
    return importlib.import_module('_attack_swig')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/seungmin/git/gr_attack/gr-attack/build/swig/_attack_swig.so: undefined symbol: _ZN2gr6attack13modified_RAPP4makeEv
<end of output>
Test time =   0.89 sec
----------------------------------------------------------
Test Failed.
"qa_random_periodic_source" end time: Oct 18 14:16 KST
"qa_random_periodic_source" time elapsed: 00:00:00
----------------------------------------------------------

2/3 Testing: qa_modified_RAPP
2/3 Test: qa_modified_RAPP
Command: "/bin/sh" "/home/seungmin/git/gr_attack/gr-attack/build/python/qa_modified_RAPP_test.sh"
Directory: /home/seungmin/git/gr_attack/gr-attack/build/python
"qa_modified_RAPP" start time: Oct 18 14:16 KST
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/seungmin/git/gr_attack/gr-attack/build/swig/attack_swig.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/seungmin/git/gr_attack/gr-attack/build/swig/_attack_swig.so: undefined symbol: _ZN2gr6attack13modified_RAPP4makeEv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seungmin/git/gr_attack/gr-attack/python/qa_modified_RAPP.py", line 24, in <module>
    import attack_swig as attack
  File "/home/seungmin/git/gr_attack/gr-attack/build/swig/attack_swig.py", line 17, in <module>
    _attack_swig = swig_import_helper()
  File "/home/seungmin/git/gr_attack/gr-attack/build/swig/attack_swig.py", line 16, in swig_import_helper
    return importlib.import_module('_attack_swig')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/seungmin/git/gr_attack/gr-attack/build/swig/_attack_swig.so: undefined symbol: _ZN2gr6attack13modified_RAPP4makeEv
<end of output>
Test time =   0.50 sec
----------------------------------------------------------
Test Failed.
"qa_modified_RAPP" end time: Oct 18 14:16 KST
"qa_modified_RAPP" time elapsed: 00:00:00
----------------------------------------------------------

3/3 Testing: qa_impairment_block
3/3 Test: qa_impairment_block
Command: "/bin/sh" "/home/seungmin/git/gr_attack/gr-attack/build/python/qa_impairment_block_test.sh"
Directory: /home/seungmin/git/gr_attack/gr-attack/build/python
"qa_impairment_block" start time: Oct 18 14:16 KST
Output:
----------------------------------------------------------
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
<end of output>
Test time =   0.47 sec
----------------------------------------------------------
Test Passed.
"qa_impairment_block" end time: Oct 18 14:16 KST
"qa_impairment_block" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Oct 18 14:16 KST
